package:
  name: vplants.lpy
  version: 2.7.0

source:
  path: ..


about:
  home: https://github.com/openalea/lpy
  license: GPL/LGPL
  summary: L-Py is a simulation software that mixes L-systems construction with the Python high-level modeling language.

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
   - python
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - vplants.plantgl
   - boost
   - qt 
   - pyqt
   - openalea.vpltk
  run:
   - vplants.plantgl
   - boost
   - qt 
   - pyqt
   - openalea.vpltk
   - ipython
   - qtconsole
   - pyopengl
   - pyqglviewer [unix]

test:
  requires:
    - nose
  imports:
    - openalea.lpy
  source_files:
    - test/
    - share/
  commands:
    - nosetests -v -I test_predecessor_at_scale.py   -I test_ui.py [unix]
    - nosetests -v -I test_predecessor_at_scale.py   -I test_ui.py -I test_axialtree.py -I test_debugger.py -I test_fibonacci.py -I test_lpytest.py -I test_matching.py [win]

