 package:
  name: vplants.lpy
  version: 2.21.1

source:
  path: ..


about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
   - python
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - vplants.plantgl
   - qt ==4.8.6 [osx]
   - qt <5 [not osx]
  run:
   - vplants.plantgl

test:
  requires:
    - nose
  imports:
    - openalea.lpy
  source_files:
    - test/test_*.py
    - test/test_*.lpy
    - test/test_*.lpy
    - test/lpytest
  commands:
   - nosetests -v -I test_predecessor_at_scale.py -I test_multiline_produce.py -I test_kwd.py -I test_fibonacci.py -I test_enviro.py -I test_nproduce.py
