package:
  name: vplants.lpy
  version: 2.7.0

source:
  path: ..


about:
  home: https://github.com/openalea/lpy
  license: CeCILL
  summary: L-Py is a simulation software that mixes L-systems construction with the Python high-level modeling language.

build:
  preserve_egg_dir: True
  number: 1

requirements:
  build:
   - python
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - openalea.plantgl
   - qt ==4.8.6 [osx]
   - qt <5 [not osx]
  run:
   - openalea.plantgl

test:
  requires:
    - nose
  imports:
    - openalea.lpy
  source_files:
    - test/
  commands:
    - nosetests -v -I test_predecessor_at_scale.py -I test_ui.py
